<?php
/**
 * Larfree Api类
 * @author xiao
 */

namespace App\Http\Controllers\Admin\Common;

use App\Models\Common\CommonApply;


use Illuminate\Http\Request;

use Larfree\Controllers\AdminApisController as Controller;


class ApplyController extends Controller {
    public $in = [
        'index' => [
            'phone' => [
                'rule' => ['sometimes'],
            ],
        ],
    ];

    public function __construct(CommonApply $model) {
        $this->model = $model;
        parent::__construct();
    }

    /**
     * @OA\Get(
     *   summary="获取所有用户",
     *   description="获取所有用户信息",
     *   path="/common/user",
     *   tags={"用户相关"},
     *   security={{
     *     "jwt":{}
     *   }},
     *   @OA\Response(
     *     response="200",
     *     description="请求成功 md5:6f90d20fcc1336029700b169c3ae2dff",
     *   ),
     * )
     */

    public function index(Request $request) {
        $this->model = $this->model->with(['type', 'user']);
        return parent::index($request); // TODO: Change the autogenerated stub
    }

    /**
     * @OA\Get(
     *   summary="获取某个用户",
     *   description="获取某个用户信息",
     *   path="/common/user/{id}",
     *   tags={"用户相关"},
     *   security={{
     *     "jwt":{}
     *   }},
     *   @OA\Response(
     *     response="200",
     *     description="请求成功 md5:6f90d20fcc1336029700b169c3ae2dff",
     *   ),
     * )
     */
    public function show($id, Request $request) {
        if ($id == 0) {
            $id = getLoginUserID();
        }

        return parent::show($id, $request);/// TODO: Change the autogenerated stub
    }

    /**
     * @OA\Post(
     *   summary="添加用户信息",
     *   description="添加用户信息",
     *   path="/common/user",
     *   tags={"用户相关"},
     *   security={{
     *     "jwt":{}
     *   }},
     *   @OA\Response(
     *     response="200",
     *     description="请求成功 md5:6067c7f9d3b741fc051dbe251c850cb0",
     *   ),
     * )
     */
    public function store(Request $request) {
        $request['invite_code'] = str_random(4);
        return parent::store($request); // TODO: Change the autogenerated stub
    }

    /**
     * @OA\Put(
     *   summary="修改用户信息",
     *   description="修改用户信息",
     *   path="/common/user/{id}",
     *   tags={"用户相关"},
     *   security={{
     *     "jwt":{}
     *   }},
     *   @OA\Response(
     *     response="200",
     *     description="请求成功 md5:51754cebd1ee823ea1716f44531c3906",
     *   ),
     * )
     */
    public function update(Request $request, $id) {


        return parent::update($request, $id); // TODO: Change the autogenerated stub
    }

    /**
     * @OA\Delete(
     *   summary="删除用户",
     *   description="删除某个用户信息",
     *   path="/common/user/{id}",
     *   tags={"用户相关"},
     *   security={{
     *     "jwt":{}
     *   }},
     *   @OA\Response(
     *     response="200",
     *     description="请求成功 md5:f28d67eccd814d4d73099bfe5ccd47f1",
     *   ),
     * )
     */
    public function destroy($id, Request $request) {
        return parent::destroy($id, $request); // TODO: Change the autogenerated stub
    }


    public function getUsersType($users, $type) {
        $returnUsers = [];
        foreach ($users as $key => $user) {
            if (!empty($user[$type])) {
                $returnUsers[] = $user;
            }
        }
        return $returnUsers;
    }


}
