<?php
/**
 * Larfree Api类
 * @author xiao
 */
namespace App\Http\Controllers\Admin\Common;

use Illuminate\Http\Request;
use Larfree\Controllers\AdminApisController as Controller;
use App\Models\Common\CommonCode;
class CodeController extends Controller
{
    public function __construct(CommonCode $model )
    {
        $this->model = $model;
        parent::__construct();
    }
    /**
     * @OA\Get(
     *   summary="查询验证码列表",
     *   description="查询验证码列表",
     *   path="/common/code",
     *   tags={"验证码相关"},
     *   security={{
     *     "jwt":{}
     *   }},
     *   @OA\Response(
     *     response="200",
     *     description="请求成功 md5:f6895bbacbd54eafc087d49ff8444792",
     *   ),
     * )
     */
    public function index(Request $request)
    {
        return parent::index($request); // TODO: Change the autogenerated stub
    }

    /**
     * @OA\Post(
     *   summary="添加验证码",
     *   description="添加验证码",
     *   path="/common/code",
     *   tags={"验证码相关"},
     *   security={{
     *     "jwt":{}
     *   }},
     *   @OA\Response(
     *     response="200",
     *     description="请求成功 md5:f6895bbacbd54eafc087d49ff8444792",
     *   ),
     * )
     */
    public function store(Request $request)
    {
        return parent::store($request); // TODO: Change the autogenerated stub
    }
    /**
     * @OA\Put(
     *   summary="修改验证码",
     *   description="修改验证码",
     *   path="/common/code",
     *   tags={"验证码相关"},
     *   security={{
     *     "jwt":{}
     *   }},
     *   @OA\Response(
     *     response="200",
     *     description="请求成功 md5:f6895bbacbd54eafc087d49ff8444792",
     *   ),
     * )
     */
    public function update(Request $request, $id)
    {
        return parent::update($request,$id); // TODO: Change the autogenerated stub
    }
    /**
     * @OA\Delete(
     *   summary="删除验证码",
     *   description="删除验证码",
     *   path="/common/code",
     *   tags={"验证码相关"},
     *   security={{
     *     "jwt":{}
     *   }},
     *   @OA\Response(
     *     response="200",
     *     description="请求成功 md5:f6895bbacbd54eafc087d49ff8444792",
     *   ),
     * )
     */
    public function destroy($id, Request $request)
    {
        return parent::destroy($id, $request); // TODO: Change the autogenerated stub
    }
}