<?php
/**
 * Larfree Api类
 * @author xiao
 */
namespace App\Http\Controllers\Admin\Common;

use App\Http\Controllers\Admin\Money\RecordController;
use App\Models\Common\CommonUser;

use App\Models\Money\MoneyRecord;
use Illuminate\Http\Request;

use Larfree\Controllers\AdminApisController as Controller;


class UserController extends Controller
{
    public $in = [
        'index' => [
            'phone' => [
                'rule' => ['sometimes'],
            ],
        ],
    ];

    public function __construct(CommonUser $model)
    {
        $this->model = $model;
        parent::__construct();
    }



    public function index(Request $request)
    {
//        $this->model->append('balance','credit_balance');


        return parent::index($request); // TODO: Change the autogenerated stub
    }


    public function show($id, Request $request)
    {
        if ($id == 0) {
            $id = getLoginUserID();
        }

        return parent::show($id, $request);/// TODO: Change the autogenerated stub
    }


    public function store(Request $request)
    {
        return parent::store($request); // TODO: Change the autogenerated stub
    }


    public function update(Request $request, $id)
    {

        return parent::update($request, $id); // TODO: Change the autogenerated stub
    }


    public function destroy($id, Request $request)
    {
        return parent::destroy($id, $request); // TODO: Change the autogenerated stub
    }


    public function changePrice(Request $request)
    {

        $user = new CommonUser();

        $res = $user->changePrice($request->all());
        if ($res ) {
            return Response()->success($res, '金额修改成功');
        }

    }


    public function getUsersType($users, $type)
    {
        $returnUsers = [];
        foreach ($users as $key => $user) {
            if (!empty($user[$type])) {
                $returnUsers[] = $user;
            }
        }
        return $returnUsers;
    }


}