<?php
/**
 * Created by PhpStorm.
 * User: xiao
 * Date: 2018/10/25
 * Time: PM4:42
 */

namespace App\Http\Controllers\Api;


use Larfree\Controllers\SwaggerController as Controller;

class SwaggerController extends Controller
{
    protected $path;
    /**
     *  返回JSON格式的Swagger定义
     *  @OA\Info(
     *     title="My First API",
     *     version="0.1"
     *  )
     *
     *  定义根路径,可多个
     *  @OA\Server(url="/api/")
     *
     *  定义认证方式
     *  @OA\SecurityScheme(
     *   securityScheme="jwt",
     *   type="apiKey",
     *   in="header",
     *   name="Authorization"
     * )
     */
    public function __construct()
    {
        $this->path =  dirname(__FILE__);
    }

    public  function getJSON()
    {
        return parent::getJSON(); // TODO: Change the autogenerated stub
    }


}