<?php
/**
 * Larfree Api类
 * @author xiao
 */

namespace App\Http\Controllers\Admin\User;

use Illuminate\Http\Request;
use Larfree\Controllers\AdminApisController as Controller;
use App\Models\User\UserActionLog;

class ActionLogController extends Controller {
    public function __construct(UserActionLog $model) {
        $this->model = $model;
        parent::__construct();
    }

    /**
     * @OA\Get(
     *   summary="查询日志列表",
     *   description="查询日志列表",
     *   path="/user/action_log",
     *   tags={"日志相关"},
     *   security={{
     *     "jwt":{}
     *   }},
     *   @OA\Response(
     *     response="200",
     *     description="请求成功 md5:ba1b8e1ac5568548ca2c2269cd9b2676",
     *   ),
     * )
     */
    public function index(Request $request) {
        return parent::index($request); // TODO: Change the autogenerated stub
    }

    /**
     * @OA\Post(
     *   summary="添加日志",
     *   description="添加日志",
     *   path="/user/action_log",
     *   tags={"日志相关"},
     *   security={{
     *     "jwt":{}
     *   }},
     *   @OA\Response(
     *     response="200",
     *     description="请求成功 md5:ba1b8e1ac5568548ca2c2269cd9b2676",
     *   ),
     * )
     */
    public function store(Request $request) {
        return parent::store($request); // TODO: Change the autogenerated stub
    }


    /**
     * @OA\Put(
     *   summary="修改日志",
     *   description="修改日志",
     *   path="/user/action_log",
     *   tags={"日志相关"},
     *   security={{
     *     "jwt":{}
     *   }},
     *   @OA\Response(
     *     response="200",
     *     description="请求成功 md5:ba1b8e1ac5568548ca2c2269cd9b2676",
     *   ),
     * )
     */
    public function update(Request $request, $id) {
        return parent::update($request, $id); // TODO: Change the autogenerated stub
    }

    /**
     * @OA\Delete(
     *   summary="删除日志",
     *   description="删除日志",
     *   path="/user/action_log",
     *   tags={"日志相关"},
     *   security={{
     *     "jwt":{}
     *   }},
     *   @OA\Response(
     *     response="200",
     *     description="请求成功 md5:ba1b8e1ac5568548ca2c2269cd9b2676",
     *   ),
     * )
     */
    public function destroy($id, Request $request) {
        return parent::destroy($id, $request); // TODO: Change the autogenerated stub
    }
}
