<?php
/**
 * Larfree Api类
 * @author xiao
 */
namespace App\Http\Controllers\Admin\User;

use Illuminate\Http\Request;
use Larfree\Controllers\AdminApisController as Controller;
use App\Models\User\UserAuth;
class AuthController extends Controller
{
    public function __construct(UserAuth $model )
    {
        $this->model = $model;
        parent::__construct();
    }
    public function store(Request $request)
    {
        return parent::store($request); // TODO: Change the autogenerated stub
    }

}