<?php
/**
 * Larfree Api类
 * @author blues
 */

namespace App\Http\Controllers\Admin\Auth;

use Illuminate\Http\Request;
use Larfree\Controllers\AdminApisController as Controller;
use App\Models\Auth\AuthRole;

class RoleController extends Controller {
    public function __construct(AuthRole $model) {
        $this->model = $model;
        parent::__construct();
    }

    public function index(Request $request) {

        return parent::index($request); // TODO: Change the autogenerated stub
    }
}
