<?php
/**
 * Larfree Api类
 * @author xiao
 */
namespace App\Http\Controllers\Api\Test;
use App\Events\ExpressMission\MissionArrived;
use App\Events\ExpressOrder\OrderCompleted;
use App\Listeners\MainVrp\Arrived;
use App\Models\Express\ExpressMission;
use App\Models\Express\ExpressOrder;
use Illuminate\Http\Request;
use Larfree\Controllers\ApisController as Controller;
use App\Models\Test\TestTest;
class TestController extends Controller
{


    public function __construct(TestTest $model)
    {
        $this->model = $model;
        parent::__construct();
    }

    public function index(Request $request)
    {


    //    $mission = ExpressMission::where('id',2694)->first();
    //    event(new MissionArrived($mission));
        setCurrentSiteId(1);
        $data=ExpressOrder::whereIn('id',['10224746','10224747'])->get();
        event(new OrderCompleted(ExpressMission::first(),$data));
//       return parent::index($request); // TODO: Change the autogenerated stub
    }
}