<?php
/**
 * 其他可以用组建默认的参数
 * 也可以自己指定
 */
return [
    'detail'=>[
        'table'=>[
            'fields'=>[
                'id',
            'name',
            'scope',
            'param',
            'rule',
            'status',
            'created_at',
            'updated_at',
            'model'
             ],
        ],
        'add'=>[
            'fields'=>[
                'name',
            'scope',
            'param',
            'rule',
            'status',
            'model'
             ],
        ],
        'edit'=>[
            'fields'=>[
                'name',
            'scope',
            'param',
            'rule',
            'status',
            'model'
            ],
        ],
        'detail'=>[
            'fields'=>[
                'id',
            'name',
            'scope',
            'param',
            'rule',
            'status',
            'created_at',
            'updated_at',
            'model'
            ],
        ],
    ],
];