<?php
/**
 * 其他可以用组建默认的参数
 * 也可以自己指定
 */
return [
    'detail'=>[
        'table'=>[
            'search'=>[
                'user_id',
                'user_type',
                'type',
                'title',
            ],
            'fields'=>[
                'id',
            'user_id',
            'user_type',
            'type',
            'ip',
            'from',
            'site',
            'after_content',
            'before_content',
            'title',
            'model',
            'created_at',
            'updated_at'
             ],
        ],
        'add'=>[
            'fields'=>[
                'user_id',
            'user_type',
            'type',
            'ip',
            'from',
            'site',
            'after_content',
            'before_content',
            'title',
            'model'
             ],
        ],
        'edit'=>[
            'fields'=>[
                'user_id',
            'user_type',
            'type',
            'ip',
            'from',
            'site',
            'after_content',
            'before_content',
            'title',
            'model'
            ],
        ],
        'detail'=>[
            'fields'=>[
                'id',
            'user_id',
            'user_type',
            'type',
            'ip',
            'from',
            'site',
            'after_content',
            'before_content',
            'title',
            'model',
            'created_at',
            'updated_at'
            ],
        ],
    ],
];