<?php
/**
 * 其他可以用组建默认的参数
 * 也可以自己指定
 */
return [
    'detail'=>[
        'table'=>[
            'fields'=>[
                'id',
            'user_id',
            'type',
            'field1',
            'field2',
            'field3',
            'image1',
            'image2',
            'created_at',
            'updated_at'
             ],
        ],
        'add'=>[
            'fields'=>[
                'user_id',
            'type',
            'field1',
            'field2',
            'field3',
            'image1',
            'image2'
             ],
        ],
        'edit'=>[
            'fields'=>[
                'user_id',
            'type',
            'field1',
            'field2',
            'field3',
            'image1',
            'image2'
            ],
        ],
        'detail'=>[
            'fields'=>[
                'id',
            'user_id',
            'type',
            'field1',
            'field2',
            'field3',
            'image1',
            'image2',
            'created_at',
            'updated_at'
            ],
        ],
    ],
];