<?php
return [
    'detail'=>[
        
            'id'=>[
                'name'=>'id',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'int(200)',
            ],
            'order_id'=>[
                'name'=>'订单号',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(150)',
            ],
            'product_id'=>[
                'name'=>'关联所属商品',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'int(100)',
            ],
            'coupon_id'=>[
                'name'=>'优惠券id',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'int(100)',
            ],
            'ord_class'=>[
                'name'=>'1自动发卡 2代充',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'int(1)',
            ],
            'product_price'=>[
                'name'=>'商品单价',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'decimal(10,2)',
            ],
            'ord_price'=>[
                'name'=>'ord_price',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'decimal(10,2)',
            ],
            'buy_amount'=>[
                'name'=>'购买数量',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'int(10)',
            ],
            'ord_title'=>[
                'name'=>'订单名称',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(200)',
            ],
            'search_pwd'=>[
                'name'=>'查询密码',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(200)',
            ],
            'account'=>[
                'name'=>'充值账号',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(200)',
            ],
            'ord_info'=>[
                'name'=>'订单详情',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'text',
            ],
            'pay_ord'=>[
                'name'=>'第三发支付id',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(200)',
            ],
            'pay_way'=>[
                'name'=>'第三方支付方式',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'int(20)',
            ],
            'buy_ip'=>[
                'name'=>'购买者ip地址',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(30)',
            ],
            'ord_status'=>[
                'name'=>'1待处理 2已处理 3已完成  4处理失败',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'int(1)',
            ],
            'created_at'=>[
                'name'=>'created_at',
                'tip'=>'',
                'type'=>'timestamp',
                'sql_type'=>'timestamp',
            ],
            'updated_at'=>[
                'name'=>'updated_at',
                'tip'=>'',
                'type'=>'timestamp',
                'sql_type'=>'timestamp',
            ],
            'wechat'=>[
                'name'=>'wechat',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(255)',
            ],
            'mobile'=>[
                'name'=>'mobile',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(255)',
            ],
            'deleted_at'=>[
                'name'=>'deleted_at',
                'tip'=>'',
                'type'=>'timestamp',
                'sql_type'=>'timestamp',
            ],
            'push_range'=>[
                'name'=>'push_range',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(255)',
            ],
            'push_day'=>[
                'name'=>'push_day',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'int(20)',
            ],
    ],
];