<?php
return [
    'detail'=>[
        
            'id'=>[
                'name'=>'id',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'int(11)',
            ],
            'pay_name'=>[
                'name'=>'pay_name',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(255)',
            ],
            'pay_check'=>[
                'name'=>'现金额度',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(255)',
            ],
            'pay_method'=>[
                'name'=>'张数',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(255)',
            ],
            'merchant_id'=>[
                'name'=>'流水号',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(255)',
            ],
            'merchant_key'=>[
                'name'=>'领取数量',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'int(11)',
            ],
            'merchant_pem'=>[
                'name'=>'merchant_pem',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(255)',
            ],
            'pay_handleroute'=>[
                'name'=>'支付类型',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(20)',
            ],
            'pay_status'=>[
                'name'=>'pay_status',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'int(3)',
            ],
            'created_at'=>[
                'name'=>'created_at',
                'tip'=>'',
                'type'=>'timestamp',
                'sql_type'=>'timestamp',
            ],
            'updated_at'=>[
                'name'=>'updated_at',
                'tip'=>'',
                'type'=>'timestamp',
                'sql_type'=>'timestamp',
            ],
    ],
];