<?php
return [
    'detail'=>[
        
            'id'=>[
                'name'=>'id',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'int(11)',
            ],
            'pd_picture'=>[
                'name'=>'商品图片',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(255)',
            ],
            'pd_name'=>[
                'name'=>'商品名称',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(255)',
            ],
            'actual_price'=>[
                'name'=>'实际售价',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'decimal(10,2)',
            ],
            'cost_price'=>[
                'name'=>'原价',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'decimal(10,2)',
            ],
            'in_stock'=>[
                'name'=>'库存',
                'tip'=>'',
                'type'=>'number',
                'sql_type'=>'bigint(255)',
            ],
            'brief_desc'=>[
                'name'=>'简介',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(255)',
            ],
            'pd_info'=>[
                'name'=>'详情',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'text',
            ],
            'sales_volume'=>[
                'name'=>'sales_volume',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'int(50)',
            ],
            'pd_type'=>[
                'name'=>'pd_type',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'int(4)',
            ],
            'isopen_coupon'=>[
                'name'=>'是否开启优惠券',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'int(1)',
            ],
            'wholesale_price'=>[
                'name'=>'批发价配置',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'text',
            ],
            'weight'=>[
                'name'=>'排序',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'int(100)',
            ],
            'status'=>[
                'name'=>'status',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'int(11)',
            ],
            'created_at'=>[
                'name'=>'created_at',
                'tip'=>'',
                'type'=>'timestamp',
                'sql_type'=>'timestamp',
            ],
            'updated_at'=>[
                'name'=>'updated_at',
                'tip'=>'',
                'type'=>'timestamp',
                'sql_type'=>'timestamp',
            ],
    ],
];