<?php
return [
    'detail'=>[
        
            'id'=>[
                'name'=>'id',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'int(10) unsigned',
            ],
            'name'=>[
                'name'=>'范围',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(255)',
            ],
            'scope'=>[
                'name'=>'scope函数',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(255)',
            ],
            'param'=>[
                'name'=>'参数',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'json',
            ],
            'rule'=>[
                'name'=>'其他规则',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(255)',
            ],
            'status'=>[
                'name'=>'有效',
                'tip'=>'',
                'type'=>'number',
                'sql_type'=>'tinyint(1)',
            ],
            'created_at'=>[
                'name'=>'created_at',
                'tip'=>'',
                'type'=>'timestamp',
                'sql_type'=>'timestamp',
            ],
            'updated_at'=>[
                'name'=>'updated_at',
                'tip'=>'',
                'type'=>'timestamp',
                'sql_type'=>'timestamp',
            ],
            'model'=>[
                'name'=>'model',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(255)',
            ],
    ],
];