<?php
return [
    'detail'=>[
        
            'id'=>[
                'name'=>'id',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'int(1)',
            ],
            'title'=>[
                'name'=>'网站标题',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(200)',
            ],
            'text_logo'=>[
                'name'=>'网站logo',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(50)',
            ],
            'img_logo'=>[
                'name'=>'网站图标',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(200)',
            ],
            'keywords'=>[
                'name'=>'网站关键词',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(200)',
            ],
            'description'=>[
                'name'=>'描述',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(200)',
            ],
            'notice'=>[
                'name'=>'notice',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'text',
            ],
            'footer'=>[
                'name'=>'footer',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'text',
            ],
            'instock'=>[
                'name'=>'instock',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'int(1)',
            ],
            'manage_email'=>[
                'name'=>'manage_email',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(50)',
            ],
            'langs'=>[
                'name'=>'langs',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(50)',
            ],
            'verify_code'=>[
                'name'=>'verify_code',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'int(1)',
            ],
            'isopen_searchpwd'=>[
                'name'=>'isopen_searchpwd',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'int(1)',
            ],
            'isopen_serverj'=>[
                'name'=>'isopen_serverj',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'int(1)',
            ],
            'serverj_token'=>[
                'name'=>'serverj_token',
                'tip'=>'',
                'type'=>'text',
                'sql_type'=>'varchar(100)',
            ],
            'created_at'=>[
                'name'=>'created_at',
                'tip'=>'',
                'type'=>'timestamp',
                'sql_type'=>'timestamp',
            ],
            'updated_at'=>[
                'name'=>'updated_at',
                'tip'=>'',
                'type'=>'timestamp',
                'sql_type'=>'timestamp',
            ],
    ],
];