<?php
/**
 * 其他可以用组建默认的参数
 * 也可以自己指定
 */
return [
    'detail'=>[
        'table'=>[
            'fields'=>[
                'id',
            'title',
            'text_logo',
            'img_logo',
            'keywords',
            'description',
            'notice',
            'footer',
            'instock',
            'manage_email',
            'langs',
            'verify_code',
            'isopen_searchpwd',
            'isopen_serverj',
            'serverj_token',
            'created_at',
            'updated_at'
             ],
        ],
        'add'=>[
            'fields'=>[
                'title',
            'text_logo',
            'img_logo',
            'keywords',
            'description',
            'notice',
            'footer',
            'instock',
            'manage_email',
            'langs',
            'verify_code',
            'isopen_searchpwd',
            'isopen_serverj',
            'serverj_token'
             ],
        ],
        'edit'=>[
            'fields'=>[
                'title',
            'text_logo',
            'img_logo',
            'keywords',
            'description',
            'notice',
            'footer',
            'instock',
            'manage_email',
            'langs',
            'verify_code',
            'isopen_searchpwd',
            'isopen_serverj',
            'serverj_token'
            ],
        ],
        'detail'=>[
            'fields'=>[
                'id',
            'title',
            'text_logo',
            'img_logo',
            'keywords',
            'description',
            'notice',
            'footer',
            'instock',
            'manage_email',
            'langs',
            'verify_code',
            'isopen_searchpwd',
            'isopen_serverj',
            'serverj_token',
            'created_at',
            'updated_at'
            ],
        ],
    ],
];