<?php
/**
 * 其他可以用组建默认的参数
 * 也可以自己指定
 */
return [
    'detail'=>[
        'table'=>[
            'fields'=>[
                'id',
            'name',
            'type',
            'url_link',
            'banner_url',
            'status',
            'created_at',
            'updated_at'
             ],
        ],
        'add'=>[
            'fields'=>[
                'name',
            'type',
            'url_link',
            'banner_url',
            'status'
             ],
        ],
        'edit'=>[
            'fields'=>[
                'name',
            'type',
            'url_link',
            'banner_url',
            'status'
            ],
        ],
        'detail'=>[
            'fields'=>[
                'id',
            'name',
            'type',
            'url_link',
            'banner_url',
            'status',
            'created_at',
            'updated_at'
            ],
        ],
    ],
];