<?php
/**
 * Larfree Api类
 * @author xiao
 */

namespace App\Http\Controllers\Api\Common;

use App\Models\Common\CommonApply;


use EasyWeChat\Kernel\Http\Response;
use Illuminate\Http\Request;

use Larfree\Controllers\ApisController as Controller;


class ApplyController extends Controller {
    public $in = [
        'index' => [
            'phone' => [
                'rule' => ['sometimes'],
            ],
        ],
    ];

    public function __construct(CommonApply $model) {
        $this->model = $model;
        parent::__construct();
    }


    /**
     * @OA\Post(
     *   summary="获取申请列表",
     *   description="获取申请列表",
     *   path="admin/auth/nav/tree",
     *   tags={"申请相关"},
     *   security={{
     *     "jwt":{}
     *   }},
     *   @OA\Response(
     *     response="200",
     *     description="发送成功",
     *   ),
     * )
     */

    public function index(Request $request) {
        LogData('用户获取申请');
        $this->model = $this->model->query()->where('user_id', getLoginUserID())->link();
        return parent::index($request); // TODO: Change the autogenerated stub
    }


    public function show($id, Request $request) {
        if ($id == 0) {
            $id = getLoginUserID();
        }

        return parent::show($id, $request);/// TODO: Change the autogenerated stub
    }


    public function store(Request $request) {

        $request['user_id'] = getLoginUserID();
        return parent::store($request); // TODO: Change the autogenerated stub
    }


    public function update(Request $request, $id) {
        $this->log = true;
        return parent::update($request, $id); // TODO: Change the autogenerated stub
    }


    public function destroy($id, Request $request) {

        return parent::destroy($id, $request); // TODO: Change the autogenerated stub
    }


}
